package bca.mbb.enums;

public enum ActionEnum {
    ADD, MODIFY, DELETE,
    PAY_INVOICE, REQUEST_FINANCE,REJECTED,CREATED,AUTHORIZED, UPLOAD_INVOICE, IMMEDIATE, POST_DATED,REPAY_FINANCE,RESERVE_LIMIT,
    CANCEL_PAY_INVOICE,CANCEL_REQUEST_FINANCE
}
