package bca.mbb.enums;

public enum StatusEnum {
    SUCCESS, PARTIALLY_SUCCESS, FAILED, WAITING_FOR_APPROVAL, RELEASED, REJECTED,
    CANCELED, IN_VERIFICATION, VERIFICATION_FAILED, PENDING, EXPIRED, IN_PROGRESS, TIMEOUT, ON_PROCESS_EXPLORE, UPDATE_1STVAL, UPDATE
}
